<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>MVC</title>
    <link href="https://fonts.googleapis.com/css?family=Caveat:700" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet">
    <link href="style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
   </head>
  <body>
    <header>
        <div class="menu">Please Register or Login into your account</div>
    </header>
    <?= isset($error) ? $error : ''?>
    <div class="container">
        <fieldset>
            <legend>Register Your Account</legend>
            <div class="grow">If you are a first time user, register here to create an account</div>
            <form class="register" method="POST">
                <div class="field">
                    <label>Email</label>
                    <input type="email" name="email" required>
                </div>
                <div class="field">
                    <label>Password</label>
                    <input type="password" name="password" required>
                </div>
                <input class="button" name="register" type="submit" value="Register">
            </form>
            <input id="invite" type="button" value="Register">
        </fieldset>
        <fieldset>
            <legend>Login</legend>
            <form method="POST">
                <div class="field">
                    <label>Email</label>
                    <input type="email" name="email" required>
                </div>
                <div class="field">
                    <label>Password</label>
                    <input type="password" name="password" required>
                </div>
                <input name="login" class="button" type="submit" value="Login">
            </form>
        </fieldset>
    </div>
    <script src="resources/jquery-3.3.1.min.js"></script>
    <script src="resources/jquery-ui.min.js"></script>
    <script src="resources/jquery.ui.touch-punch.min.js"></script>
    <script src="script.js"></script>
  </body>
</html>